apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "8970797855:AAEV462d7BztmsH7yZmCnhxnz-91wG_ihG0"
  TELEGRAM_CHAT_ID: "-1003919810046"
